function_body_length: 300
type_body_length: 300
disabled_rules:
- line_length
- trailing_whitespace
- vertical_whitespace
- force_cast
- multiple_closures_with_trailing_closure
- identifier_name

included:
excluded:
- Pods
